{{- if and .Values.secretEnv.create (not .Values.existingSecretEnv.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pts-document-storage-service.secretName" . }}
  labels:
    {{- include "pts-document-storage-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
