spring.application.name=pts-document-storage-service
#logging
logging.pattern.console=%clr(%d{MM-dd-yy | HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n
logging.level.org.apache.http.NoHttpResponseException=OFF
logging.level.java.net.SocketTimeoutException=OFF
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.java.net.HttpURLConnection=DEBUG
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=health,info,metrics,httptrace,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
minio.url=
minio.login=
minio.password=
minio.region=
minio.img.bucket.name=
minio.img.signature.duration=
#http
server.http2.enabled=true
#---
spring.config.activate.on-profile=prod
server.port=
minio.url=
minio.login=
minio.password=
minio.region=
minio.img.bucket-name=
minio.img.signature.duration=
#---
spring.config.activate.on-profile=dev
server.port=8094
minio.url=${MINIO_URL}
minio.login=${MINIO_LOGIN}
minio.password=${MINIO_PASSWORD}
minio.region=${MINIO_REGION}
minio.img.bucket-name=${MINIO_IMG_BUCKET_NAME}
minio.img.signature.duration=${MINIO_IMG_SIGNATURE_DURATION}