spring.application.name=pts-document-storage-service
spring.main.web-application-type=reactive
server.port=0
#logging
logging.pattern.console=%clr(%d{MM-dd-yy | HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n
logging.level.org.springframework.web.client.RestTemplate=WARN
logging.level.java.net.HttpURLConnection=WARN
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.data.repository.config=WARN
logging.level.org.springframework.kafka=WARN
# multithreading semaphore DANGER!!!!
application.upload-document-process-semaphore-settings.permits=${UPLOAD_DOCUMENT_PROCESS_SEMAPHORE_PERMITS:2}
application.get-document-process-semaphore-settings.permits=${GET_DOCUMENT_PROCESS_SEMAPHORE_PERMITS:5}
application.delete-document-process-semaphore-settings.permits=${DELETE_DOCUMENT_PROCESS_SEMAPHORE_PERMITS:1}
application.update-job-status-process-semaphore-settings.permits=${UPDATE_JOB_STATUS_PROCESS_SEMAPHORE_PERMITS:1}
# multithreading executor DANGER!!!!
application.document-service-executor-settings.core-pool-size=${DOCUMENT_SERVICE_EXECUTOR_CORE_POOL_SIZE:5}
application.document-service-executor-settings.max-pool-size=${DOCUMENT_SERVICE_EXECUTOR_MAX_POOL_SIZE:5}
application.document-service-executor-settings.queue-capacity=${DOCUMENT_SERVICE_EXECUTOR_QUEUE_CAPACITY:100}
application.upload-document-process-executor-settings.core-pool-size=${UPLOAD_DOCUMENT_PROCESS_EXECUTOR_CORE_POOL_SIZE:2}
application.upload-document-process-executor-settings.max-pool-size=${UPLOAD_DOCUMENT_PROCESS_EXECUTOR_MAX_POOL_SIZE:4}
application.upload-document-process-executor-settings.queue-capacity=${UPLOAD_DOCUMENT_PROCESS_EXECUTOR_QUEUE_CAPACITY:5}
application.get-document-process-executor-settings.core-pool-size=${GET_DOCUMENT_PROCESS_EXECUTOR_CORE_POOL_SIZE:2}
application.get-document-process-executor-settings.max-pool-size=${GET_DOCUMENT_PROCESS_EXECUTOR_MAX_POOL_SIZE:5}
application.get-document-process-executor-settings.queue-capacity=${GET_DOCUMENT_PROCESS_EXECUTOR_QUEUE_CAPACITY:5}
# metrics
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
#datasource
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.data-source-properties.socketTimeout=30
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/master.yaml
spring.liquibase.drop-first=false
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=document_storage_schema
#minio
minio.url=${MINIO_URL}
minio.login=${MINIO_LOGIN}
minio.password=${MINIO_PASSWORD}
minio.region=${MINIO_REGION}
minio.document-persistence-bucket.bucket-name=${DOCUMENT_PERSISTENCE_BUCKET_NAME}
minio.document-persistence-bucket.signature-duration=1
minio.document-temp-bucket.bucket-name=${DOCUMENT_TEMP_BUCKET_NAME}
minio.document-temp-bucket.signature-duration=1
minio.sdk-config.api-call-attempt-timeout=10
minio.sdk-config.api-call-timeout=60
minio.client-config.connection-timeout=5
minio.client-config.read-timeout=30
minio.client-config.write-timeout=30
#Kafka connection
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.admin.fail-fast=true
#Kafka producer
spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.transaction-id-prefix=doc-storage-tx-
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.retries=2147483647
spring.kafka.properties.default.api.timeout.ms=30000
spring.kafka.producer.properties.max.block.ms=10000
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.compression.type=zstd
spring.kafka.producer.properties.linger.ms=10
spring.kafka.producer.properties.batch.size=65536
#Kafka consumer
spring.kafka.consumer.group-id=document-storage-service
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=true
spring.kafka.consumer.isolation-level=read_committed
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=latest
#Kafka listener
spring.kafka.listener.ack-mode=record
spring.kafka.listener.concurrency=${KAFKA_LISTENER_CONCURRENCY:1}
#Kafka topics
app.kafka.topic.document-events-topic.name=${DOCUMENT_EVENTS_TOPIC_NAME:document-events}
app.kafka.topic.document-events-topic.partitions=${DOCUMENT_EVENTS_TOPIC_PARTITIONS:6}
app.kafka.topic.document-events-topic.replicas=${DOCUMENT_EVENTS_TOPIC_REPLICAS}
app.kafka.topic.document-commands-topic.name=${DOCUMENT_COMMANDS_TOPIC_NAME:document-commands}
app.kafka.topic.document-commands-topic.partitions=${DOCUMENT_COMMANDS_TOPIC_PARTITIONS:6}
app.kafka.topic.document-commands-topic.replicas=${DOCUMENT_COMMANDS_TOPIC_REPLICAS}
# Security
security.master-key=${MASTER_KEY}
#---
spring.config.activate.on-profile=prod
logging.level.org.springframework.web.client.RestTemplate=INFO
logging.level.java.net.HttpURLConnection=INFO
spring.datasource.hikari.maximum-pool-size=${DATASOURCE_MAX_POOL_SIZE:20}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=${DATASOURCE_DEFAULT_SCHEMA:document_storage_schema}
#---
spring.config.activate.on-profile=dev
spring.kafka.listener.auto-startup=true
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.java.net.HttpURLConnection=DEBUG
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=document_storage_schema
app.kafka.topic.document-events-topic.name=document-events
app.kafka.topic.document-events-topic.partitions=6
app.kafka.topic.document-events-topic.replicas=1
app.kafka.topic.document-commands-topic.name=document-commands
app.kafka.topic.document-commands-topic.partitions=6
app.kafka.topic.document-commands-topic.replicas=1
spring.kafka.listener.concurrency=2
management.server.port=${MANAGEMENT_SERVER_PORT:8081}
management.server.address=127.0.0.1
#---
spring.config.activate.on-profile=test
spring.kafka.listener.auto-startup=true
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.java.net.HttpURLConnection=DEBUG
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=document_storage_schema
app.kafka.topic.document-events-topic.name=document-events
app.kafka.topic.document-events-topic.partitions=6
app.kafka.topic.document-events-topic.replicas=1
app.kafka.topic.document-commands-topic.name=document-commands
app.kafka.topic.document-commands-topic.partitions=6
app.kafka.topic.document-commands-topic.replicas=1
spring.kafka.listener.concurrency=2
management.server.port=${MANAGEMENT_SERVER_PORT:8081}
management.server.address=127.0.0.1