replicaCount: 1

image:
  repository: localhost:5000/pts-document-storage-service
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001

service:
  type: ClusterIP
  port: 8094

containerPort: 8094

env:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "8094"
  MINIO_URL: "http://minio.dev.svc.cluster.local:9000"
  MINIO_REGION: ""
  MINIO_IMG_BUCKET_NAME: ""
  MINIO_IMG_SIGNATURE_DURATION: "3600"

secretEnv:
  create: false
  name: ""
  values:
    MINIO_LOGIN: ""
    MINIO_PASSWORD: ""

existingSecretEnv:
  name: pts-document-storage-service-s3-credentials
  keys:
    MINIO_LOGIN: S3_ACCESS_KEY
    MINIO_PASSWORD: S3_SECRET_KEY

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
