version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.19
    container_name: pts-vault
    ports:
      - "8200:8200"

    cap_add:
      - IPC_LOCK

    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

    command: server -dev

    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: pts-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: pts-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pts
      POSTGRES_USER: pts-admin
      POSTGRES_PASSWORD: pts-admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pts-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pts-admin -d pts" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements

  pgadmin:
    image: dpage/pgadmin4
    container_name: pts-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pts-net
    depends_on:
      - postgres

  minio:
    image: minio/minio:latest
    container_name: pts-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - pts-net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: pts-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Web UI

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: pts-kafka
    hostname: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9094,CONTROLLER://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "abcdef0123456789abcdef"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./data:/tmp/kraft-combined-logs
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 5s
      retries: 12
      start_period: 10s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: pts-kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094   # внутри Docker
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""                  # для KRaft — пусто
    depends_on:
      kafka:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: pts-prometheus
    ports:
      - "9098:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pts-net

  grafana:
    image: grafana/grafana
    container_name: pts-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - pts-net

volumes:
  postgres-data:
  pgadmin-data:
  rabbitmq_data:

networks:
  pts-net: